version: "3.9"
services:
 football:
  image: lucilas/api-eindproject
  ports:
    - "8000:8000"
  volumes:
    - sqlite_pl_volume:/code/sqlitedb
  depends_on:
    - activemq-lucassyroit
  environment:
      - ACTIVE_MQ_BROKER_URL=tcp://activemq-lucassyroit:61616?wireFormat.maxFrameSize=1048576000
 activemq-lucassyroit:
   image: rmohr/activemq:5.15.9
   ports:
     - "61616:61616"
     - "8161:8161"
   environment:
     ACTIVEMQ_NAME: activemq-lucassyroit
     ACTIVEMQ_ADMIN_LOGIN: admin
     ACTIVEMQ_ADMIN_PASSWORD: admin

volumes:
  sqlite_pl_volume: