name: Deliver container

on: push

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install uvicorn
          pip install pytest
          pip install argon2_cffi
          pip install python-jose[cryptography]
          pip install python-multipart

      - name: Create SQLite database
        run: |
          cd myproject
          mkdir -p sqlitedb
          sqlite3 sqlitedb/data.db ".databases"

      - name: Start Uvicorn server
        run: |
          cd myproject
          uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 10

      - name: Run tests
        run: pytest test_main.py

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/api-eindproject:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/api-eindproject:latest
